### ISSUE TITLE
Status Monitor update needed

### ISSUE THREAD

**Issue by seanksullivan** [Microsoft/ApplicationInsights-Announcements#18]
When will the Application Insights Status Monitor get updated to a version greater than 2.4.0 or 2.4.1?  We need the latest, so that there is support for dependency tracking from HttpClient async calls.

Does the Application Insights Status Monitor code exist within GitHub?

**Comment by MS-TimothyMothra** [comment]
We don't have any updates planned for Status Monitor.

I've found your name on several repos asking about Status Monitor.
I'm happy to see you're passionate about or product and I would love you to join the conversation on #21 and help shape the direction of Status Monitor's replacement, IIS Configurator.
