### ISSUE TITLE
is there any support for nginx+ in application insight?

### ISSUE THREAD

**Issue by yogeshgoel2020** [microsoft/ApplicationInsights-Announcements#30]

**Comment by aelmanaa** [comment]
Good question. feels like for the moment you have to do a custom development to collect events from Nginx and send them to Application insights

**Comment by aelmanaa** [comment]
@cijothomas just close without justification ? As a matter of fact , thought it was a good question . We have similar needs

**Comment by cijothomas** [comment]
This repo is for announcements only.
If you have feature requests, open in respective language repos. 
Or in general , here: https://feedback.azure.com/forums/357324-azure-monitor-application-insights
